"""Offline tests for temporal memory (timeline-based retrieval)."""

from __future__ import annotations

import time
from unittest.mock import patch

from morainet.memory.temporal import (
    EntryKind,
    TemporalEntry,
    TemporalMemory,
    _format_timestamp,
)


def test_entry_id_autogenerated_and_preserved():
    e = TemporalEntry(timestamp=1000.0, kind=EntryKind.EVENT, title="x")
    assert e.entry_id == "event_1000000"
    e2 = TemporalEntry(timestamp=1.0, kind=EntryKind.DECISION, title="y", entry_id="custom")
    assert e2.entry_id == "custom"


def test_format_timestamp_returns_string():
    assert isinstance(_format_timestamp(0.0), str)


class TestTemporalMemory:
    def setup_method(self):
        self.mem = TemporalMemory()

    def test_record_event(self):
        e = self.mem.record("did thing", kind=EntryKind.EVENT)
        assert e.kind == EntryKind.EVENT
        assert len(self.mem) == 1

    def test_record_decision(self):
        e = self.mem.record_decision("chose X")
        assert e.kind == EntryKind.DECISION

    def test_record_milestone(self):
        e = self.mem.record_milestone("v1 shipped")
        assert e.kind == EntryKind.MILESTONE

    def test_record_run_truncates_description(self):
        e = self.mem.record_run("query", "a" * 500)
        assert e.kind == EntryKind.RUN
        assert len(e.description) == 200

    def test_timeline_reverse_chronological(self):
        with patch.object(time, "time", side_effect=[1.0, 2.0, 3.0]):
            self.mem.record("a")
            self.mem.record("b")
            self.mem.record("c")
        tl = self.mem.timeline()
        assert [e.timestamp for e in tl] == [3.0, 2.0, 1.0]

    def test_timeline_kind_filter(self):
        with patch.object(time, "time", side_effect=[1.0, 2.0, 3.0]):
            self.mem.record("e1", kind=EntryKind.EVENT)
            self.mem.record_decision("d1")
            self.mem.record("e2", kind=EntryKind.EVENT)
        assert len(self.mem.decisions()) == 1
        assert len(self.mem.recent_runs()) == 0

    def test_timeline_since_until(self):
        with patch.object(time, "time", side_effect=[10.0, 20.0, 30.0]):
            self.mem.record("old", kind=EntryKind.EVENT)
            self.mem.record("mid", kind=EntryKind.EVENT)
            self.mem.record("new", kind=EntryKind.EVENT)
        res = self.mem.timeline(since=15.0, until=25.0)
        titles = [e.title for e in res]
        assert "mid" in titles
        assert "old" not in titles
        assert "new" not in titles

    def test_search_by_title_and_tag(self):
        self.mem.record("Deploy to prod", kind=EntryKind.EVENT, tags=["ops"])
        assert len(self.mem.search("Deploy")) == 1
        assert len(self.mem.search("ops", kind=EntryKind.EVENT)) == 1

    def test_review_history_window(self):
        now = time.time()
        with patch.object(time, "time", side_effect=[now - 100, now]):
            self.mem.record_decision("decision A")
            self.mem.record_decision("recent decision")
        assert len(self.mem.review_history("decision", window_days=30)) == 2

    def test_by_tag(self):
        self.mem.record("x", tags=["a"])
        self.mem.record("y", tags=["b"])
        assert len(self.mem.by_tag("a")) == 1

    def test_stats_counts_by_kind(self):
        self.mem.record("e", kind=EntryKind.EVENT)
        self.mem.record_decision("d")
        s = self.mem.stats()
        assert s["event"] == 1
        assert s["decision"] == 1

    def test_to_messages_empty_and_nonempty(self):
        assert self.mem.to_messages() == []
        self.mem.record_decision("pick framework")
        msgs = self.mem.to_messages()
        assert len(msgs) == 1
        assert "pick framework" in msgs[0].content

    def test_trim_respects_max_entries(self):
        mem = TemporalMemory(max_entries=2)
        mem.record("a")
        mem.record("b")
        mem.record("c")
        assert len(mem) == 2
        assert "a" not in [e.title for e in mem._entries]
